=== cte-zl-ifrn/integration-integrador_ava/src/integrador/static/SUDiario.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/SUDiario",
    "definitions": {
        "SUDiario": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "polo": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/PoloCompleto"
                        }
                    ]
                },
                "campus": {
                    "$ref": "#/definitions/Campus"
                },
                "curso": {
                    "$ref": "#/definitions/Curso"
                },
                "turma": {
                    "$ref": "#/definitions/Turma"
                },
                "componente": {
                    "$ref": "#/definitions/Componente"
                },
                "diario": {
                    "$ref": "#/definitions/Diario"
                },
                "alunos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Aluno"
                    }
                },
                "professores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Professor"
                    }
                },
                "equipe": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/MembroEquipe"
                    }
                }
            },
            "required": [
                "campus",
                "componente",
                "curso",
                "diario",
                "turma"
            ],
            "title": "SUDiario"
        },
        "Campus": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "sigla": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "sigla",
                "descricao"
            ],
            "title": "Campus"
        },
        "Curso": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "codigo": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "descricao_historico": {
                    "type": "string"
                },
                "titulo_certificado_masculino": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "titulo_certificado_feminino": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "ch_total": {
                    "type": [
                        "number",
                        "null"
                    ]
                },
                "ch_aula": {
                    "type": [
                        "number",
                        "null"
                    ]
                },
                "conteudo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ConteudoCurso"
                    }
                },
                "autoinstrucional": {
                    "type": "boolean"
                },
                "modalidade": {
                    "$ref": "#/definitions/Modalidade"
                },
                "auto_inscricao": {
                    "type": "boolean"
                },
                "restricoes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/RestricaoCurso"
                    }
                },
                "programa": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "codigo",
                "nome"
            ],
            "title": "Curso"
        },
        "ConteudoCurso": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "descricao": {
                    "type": "string"
                },
                "ch": {
                    "type": "number"
                }
            },
            "required": [
                "ch",
                "descricao"
            ],
            "title": "ConteudoCurso"
        },
        "Modalidade": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "descricao": {
                    "type": "string"
                },
                "nivel_ensino": {
                    "$ref": "#/definitions/NivelEnsino"
                }
            },
            "required": [
                "descricao",
                "id"
            ],
            "title": "Modalidade"
        },
        "NivelEnsino": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "descricao": {
                    "type": "string"
                }
            },
            "required": [
                "descricao",
                "id"
            ],
            "title": "NivelEnsino"
        },
        "RestricaoCurso": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "descricao": {
                    "type": "string"
                },
                "chave": {
                    "type": "string"
                },
                "restricao": {
                    "type": "string"
                }
            },
            "required": [
                "chave",
                "descricao",
                "restricao"
            ],
            "title": "RestricaoCurso"
        },
        "Turma": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "codigo": {
                    "type": "string"
                },
                "data_inicio": {
                    "type": "string",
                    "format": "date"
                },
                "data_fim": {
                    "type": "string",
                    "format": "date"
                },
                "gerar_matricula": {
                    "type": "boolean"
                },
                "modelo_padrao": {
                    "type": "boolean"
                },
                "nota_minima": {
                    "type": "number"
                },
                "completude_minima": {
                    "type": "number"
                }
            },
            "required": [
                "id",
                "codigo"
            ],
            "title": "Turma"
        },
        "Componente": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "tipo": {
                    "type": "integer"
                },
                "sigla": {
                    "type": "string"
                },
                "periodo": {
                    "type": [
                        "integer",
                        "null"
                    ]
                },
                "optativo": {
                    "type": "boolean"
                },
                "descricao": {
                    "type": "string"
                },
                "qtd_avaliacoes": {
                    "type": "integer"
                },
                "descricao_historico": {
                    "type": "string"
                },
                "is_seminario_estagio_docente": {
                    "type": "boolean"
                },
                "ch_presencial": {
                    "type": "number"
                },
                "ch_pratica": {
                    "type": "number"
                },
                "ch_extensao": {
                    "type": "number"
                },
                "ch_pcc": {
                    "type": "number"
                },
                "ch_visita_tecnica": {
                    "type": "number"
                },
                "ch_semanal_1s": {
                    "type": "number"
                },
                "ch_semanal_2s": {
                    "type": "number"
                }
            },
            "required": [
                "id",
                "sigla",
                "descricao"
            ],
            "title": "Componente"
        },
        "Diario": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "tipo": {
                    "type": "string"
                },
                "sigla": {
                    "type": "string"
                },
                "situacao": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "descricao_historico": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "sigla",
                "situacao"
            ],
            "title": "Diario"
        },
        "Aluno": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_secundario": {
                    "type": "string"
                },
                "programa": {
                    "type": "string"
                },
                "situacao_diario": {
                    "type": "string",
                    "enum": [
                        "ativo",
                        "inativo",
                        "Ativo",
                        "Inativo"
                    ]
                },
                "polo": {
                    "$ref": "#/definitions/PoloBasico"
                },
                "situacao": {
                    "type": "string"
                },
                "matricula": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "ativo": {
                    "type": "boolean"
                },
                "nome_usual": {
                    "type": "string"
                },
                "nome_social": {
                    "type": "string"
                },
                "nome_registro": {
                    "type": "string"
                },
                "cpf": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "outras_matriculas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OutraMatricula"
                    }
                },
                "passaporte": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "required": [
                "email",
                "email_secundario",
                "id",
                "matricula",
                "nome",
                "polo",
                "situacao"
            ],
            "title": "Aluno"
        },
        "OutraMatricula": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "identificacao": {
                    "type": "string"
                },
                "curso": {
                    "$ref": "#/definitions/CursoResumo"
                }
            },
            "required": [
                "curso",
                "identificacao"
            ],
            "title": "OutraMatricula"
        },
        "CursoResumo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "codigo": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            },
            "required": [
                "codigo",
                "id",
                "nome"
            ],
            "title": "CursoResumo"
        },
        "Professor": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_secundario": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "ativo": {
                    "type": "boolean"
                },
                "nome_usual": {
                    "type": "string"
                },
                "nome_social": {
                    "type": "string"
                },
                "nome_registro": {
                    "type": "string"
                },
                "eh_servidor": {
                    "type": "boolean"
                },
                "eh_aluno": {
                    "type": "boolean"
                },
                "eh_prestador": {
                    "type": "boolean"
                },
                "eh_usuarioexterno": {
                    "type": "boolean"
                },
                "eh_docente": {
                    "type": "boolean"
                },
                "eh_tecnico_administrativo": {
                    "type": "boolean"
                },
                "eh_estrangeiro": {
                    "type": "boolean"
                },
                "cpf": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "passaporte": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "required": [
                "email",
                "email_secundario",
                "id",
                "login",
                "nome",
                "status",
                "tipo"
            ],
            "title": "Professor"
        },
        "MembroEquipe": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "username": {
                    "type": "string"
                },
                "ativo": {
                    "type": "boolean"
                },
                "eh_servidor": {
                    "type": "boolean"
                },
                "eh_aluno": {
                    "type": "boolean"
                },
                "eh_prestador": {
                    "type": "boolean"
                },
                "eh_usuarioexterno": {
                    "type": "boolean"
                },
                "eh_docente": {
                    "type": "boolean"
                },
                "eh_tecnico_administrativo": {
                    "type": "boolean"
                },
                "eh_estrangeiro": {
                    "type": "boolean"
                },
                "nome": {
                    "type": "string"
                },
                "nome_usual": {
                    "type": "string"
                },
                "nome_social": {
                    "type": "string"
                },
                "nome_registro": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_secundario": {
                    "type": "string"
                },
                "cpf": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "passaporte": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "papeis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/PapelEquipe"
                    }
                }
            },
            "required": [
                "ativo",
                "email",
                "nome",
                "papeis",
                "username"
            ],
            "title": "MembroEquipe"
        },
        "PapelEquipe": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "descricao": {
                    "type": "string"
                },
                "polo": {
                    "$ref": "#/definitions/PoloCompleto"
                }
            },
            "required": [
                "descricao",
                "id",
                "polo"
            ],
            "title": "PapelEquipe"
        },
        "PoloBasico": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "descricao": {
                    "type": "string"
                },
                "sigla": {
                    "type": "string"
                }
            },
            "required": [
                "descricao",
                "id"
            ],
            "title": "PoloBasico"
        },
        "PoloCompleto": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "sigla": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                }
            },
            "required": [
                "descricao",
                "id",
                "sigla"
            ],
            "title": "PoloCompleto"
        }
    }
}

=== cte-zl-ifrn/integration-integrador_ava/example/data.json
{
    "polo": null,
    "curso": {
        "id": 12,
        "nome": "Tecnologia em Gestão Ambiental",
        "codigo": "12345",
        "descricao": "Tecnologia em Gestão Ambiental EaD [2012] - Campus EaD (UAB)"
    },
    "turma": {
        "id": 1234,
        "codigo": "2025.3.18.1234"
    },
    "alunos": [
        {
            "id": 13,
            "nome": "João Da Silva",
            "polo": {
                "id": 1,
                "descricao": "Polo Central"
            },
            "email": "joaosilva@academico.ifrn.edu.br",
            "programa": "UAB",
            "situacao": "ativo",
            "matricula": "2023123",
            "situacao_diario": "ativo",
            "email_secundario": "joaosilva@gmail.com"
        },
        {
            "id": 351443,
            "nome": "Maria da Silva",
            "polo": {
                "id": 31,
                "descricao": "Parelhas"
            },
            "email": "",
            "programa": "UAB",
            "situacao": "ativo",
            "matricula": "2023124",
            "situacao_diario": "ativo",
            "email_secundario": "mariasilva@hotmail.com"
        }
    ],
    "campus": {
        "id": 14,
        "sigla": "ZL",
        "descricao": "CAMPUS AVANÇADO NATAL-ZONA LESTE"
    },
    "diario": {
        "id": 123,
        "sigla": "MIC.AMB",
        "situacao": "Aberto",
        "descricao": "Microbiologia Ambiental(60H)",
        "descricao_historico": "Microbiologia Ambiental"
    },
    "componente": {
        "id": 15,
        "tipo": 1,
        "sigla": "MIC.AMB",
        "periodo": 3,
        "optativo": false,
        "descricao": "Microbiologia Ambiental(60H)",
        "qtd_avaliacoes": 2,
        "descricao_historico": "Microbiologia Ambiental"
    },
    "professores": [
        {
            "id": 157706,
            "nome": "João Maria",
            "tipo": "Principal",
            "email": "joaomaria@ifrn.edu.br",
            "login": "123456",
            "status": "ativo",
            "email_secundario": ""
        }
    ]
}
